apiVersion: v1
kind: Service
metadata:
  name: {{ include "stateful-data-generator.fullname" . }}-service
  namespace: {{ include "stateful-data-generator.namespace" . }}
  labels:
    {{- include "stateful-data-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "stateful-data-generator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
