# Default values for stateful-data-generator
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

# Global configuration
global:
  namespace: ""  # If empty, uses the release namespace

# Namespace creation
namespaceCreate: false  # Set to true to create the namespace if it doesn't exist

# Application configuration
app:
  name: stateful-app
  replicaCount: 2
  image:
    repository: ghcr.io/talhajuikar/stateful-data-generator
    tag: "v1.1.1"
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 80
    targetPort: 3000
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  # Health checks
  livenessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
  
  readinessProbe:
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 10

# MongoDB configuration
mongodb:
  enabled: true
  name: mongodb
  image:
    repository: mongo
    tag: "4.4"
    pullPolicy: IfNotPresent
  
  service:
    port: 27017
    type: ClusterIP
  
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Environment variables
env:
  mongodbUri: "mongodb://mongodb-service:27017/statefulapp"

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod security context
podSecurityContext: {}

# Security context
securityContext: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}
